
name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust the branch to match your deployment branch

jobs:
  deploy:
    name: Deploy Rails App to EC2
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2  # Adjust Ruby version to your project's requirements
          bundler-cache: true

      # Install dependencies
      - name: Install dependencies
        run: bundle install

      # Run tests (optional, skip if you don't want to test before deployment)
      - name: Run tests
        run: bin/rails test

      # Deploy to EC2
      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Add EC2's SSH key to the SSH agent
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Define deployment directory on EC2
          DEPLOY_DIR=/var/www/rails_app

          # Transfer application code to EC2
          scp -i private_key.pem -r . $EC2_USER@$EC2_HOST:$DEPLOY_DIR

          # SSH into EC2 and restart the application
          ssh -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd $DEPLOY_DIR
          bundle install
          RAILS_ENV=production bin/rails assets:precompile
          RAILS_ENV=production bin/rails db:migrate
          sudo systemctl restart rails_app  # Update with your Rails app service name
          EOF

      # Clean up private key
      - name: Clean up
        run: rm -f private_key.pem