
name: Deploy Economiser to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Rails App to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true

      # Step 3: Navigate to `economy_manager` and install dependencies
      - name: Install dependencies
        run: |
          cd economy_manager
          bundle install

      # Step 4: Ensure Rails bin files have execution permissions
      - name: Fix Rails permissions
        run: |
          cd economy_manager
          chmod +x bin/rails

      # Step 5: Run database migrations (optional: skip if not needed for deployment)
      - name: Set up database
        env:
          PATH: ${{ steps.setup-ruby.outputs.ruby-path }}/bin:$PATH
        run: |
          cd economy_manager
          bin/rails db:migrate RAILS_ENV=production

      # Step 6: Precompile assets
      - name: Precompile assets
        env:
          PATH: ${{ steps.setup-ruby.outputs.ruby-path }}/bin:$PATH
        run: |
          cd economy_manager
          bin/rails assets:precompile RAILS_ENV=production

      # Step 7: Deploy to EC2
      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          DEPLOY_DIR=/var/www/economiser

          # Transfer the application files to the EC2 instance
          scp -i private_key.pem -r ./economy_manager $EC2_USER@$EC2_HOST:$DEPLOY_DIR

          # SSH into the EC2 instance and finalize the deployment
          ssh -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd $DEPLOY_DIR
          bundle install
          RAILS_ENV=production bin/rails db:migrate
          RAILS_ENV=production bin/rails assets:precompile
          sudo systemctl restart economiser # Replace with the actual service name if different
          EOF

      # Step 8: Clean up sensitive data
      - name: Clean up
        run: rm -f private_key.pem